[package]
name = "zephyr-rust-wrappers"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zephyr = { path = "/workingdir/zephyr-rust/rust/zephyr" }